### ISSUE TITLE
[buvanesh2022re] Unresolved citation and improper format for header 

### ISSUE THREAD

**Issue by anirudhb11** [ReScience/MLRC#48]
# Referring to our code in PR #47 

We are facing the following issues:

## Improper format for header (header overlaps with main content)
<img width="839" alt="Screenshot 2022-04-24 at 12 47 20 PM" src="https://user-images.githubusercontent.com/39529765/164964786-a0641474-600e-471c-891f-2763cbd4a61c.png">

## Citation references undefined
We see errors the following errors during build: 

```
LaTeX Warning: Citation 'zhuang_adabelief_2020' on page 3 undefined on input li
ne 62.
 
 
LaTeX Warning: Citation 'SGD' on page 3 undefined on input line 73.
 
 
LaTeX Warning: Citation 'Momentum' on page 3 undefined on input line 73.
 
 
LaTeX Warning: Citation 'NAG' on page 3 undefined on input line 73.
 
 
LaTeX Warning: Citation 'Adam' on page 3 undefined on input line 73.
 
 
LaTeX Warning: Citation 'liu_variance_2020' on page 3 undefined on input line 7
3.
```

## References to tables, images, sections are not resolved
Whatever is referred using `\ref` command appears as `??` in the pdf

## make[1]: *** No rule to make target `article.bbl'
[STDOUT Logs of build-all.sh](https://pastebin.com/3trev36j)

[build.log file](https://pastebin.com/XAmjafx2)

 Thanks for your help.

**Comment by koustuvsinha** [comment]
Possible `natbib` issue, added a note in the PR!

**Comment by mdrpanwar** [comment]
Leaving this note for future visitors to this issue: To resolve the issues mentioned above, please follow the steps mentioned by @koustuvsinha in [this comment](https://github.com/ReScience/MLRC/pull/47#issuecomment-1111653503).
