### ISSUE TITLE
[togt2022badder] Some questions

### ISSUE THREAD

**Issue by thesofakillers** [ReScience/MLRC#49]
Hi, we are going through the process of preparing our pull requests. Some questions:

1. There is a typo in our title metadata ([link](https://github.com/ReScience/MLRC/blob/a5e80ecba0df11f9425d1389a3fcf1eb6f08f08e/2021/accepted.bib#L365-L366)) (I think inherited from openreview, this is our fault, sorry): there is a missing space between "Methods" and "for", resulting in "Methodsfor". I can fix this as part of my pull request of course. Would that be ok?
2. On the topic of the title, i see from the checklist that the title should start with "_[RE]_". We weren't aware of this requirement in the openreview process and as a result our title is different. Should we change it to include "_[RE]_"? I.e. is this a hard constraint? If so, I suppose we should also definitely change it in the accepted.bib file? Or will that mess with the key?

Thanks

**Comment by thesofakillers** [comment]
Also, what should we commit to the PR? Just the contents of the <paper_citekey> folder?

**Comment by koustuvsinha** [comment]
Hi @thesofakillers,
1. Yes it would be perfectly okay.
2. No worries, the requirement of title to start with `[Re]` is specific to ReScience. You should change the title now but only for the camera ready process (no need to update in OpenReview/accepted.bib).
3. Yes, you should commit only the contents of `<paper_citeky>` folder.

**Comment by thesofakillers** [comment]
Ok thanks. I've submitted the PR :)
