### ISSUE TITLE
check_title function

### ISSUE THREAD

**Issue by nils2** [ReScience/MLRC#58]
Hi,
Our paper got accepted but we failed to reproduce the results.
As suggested in the metadata.yaml we now have the following title:
"[¬Re] Reproducing 'Fair Selective Classification via Sufficiency'"
However, the check_yaml.py won't accept this as a correct title.
The check_title function only passes for "[Re] " but does not consider our case.
Could I suggest changing the code to:
`def check_title(meta):
    check_ne(meta, "title", "Metadata")
    assert meta["title"].startswith(
        "[Re] "
    ) or meta["title"].startswith(
        "[¬Re] "
    ), "title in metadata should start with '[Re]' or '[¬Re]'" `

Or is [Re] correct in our situation?
Thanks

**Comment by koustuvsinha** [comment]
Thanks for pointing it out! I have changed the checker to include both `[Re]` and `[¬Re]` as per your suggestion!
