### ISSUE TITLE
Help needed to understand the whole process. 

### ISSUE THREAD

**Issue by wi25hoy** [ReScience/MLRC#68]
Since i am lacking  in basics, and this is my first ever paper. i would like someone to guide me through the process as written guidelines bit confusing to me.  i am really looking forward to get your help in order to timely submission of camera ready version. 

regards
Waqas Ahmed

**Comment by koustuvsinha** [comment]
Hi Waqas, can you let me know which part you are stuck? Are you able to create a folder using `setup.sh` and place your latex source files in `openreview` folder?

**Comment by wi25hoy** [comment]
hi,

I will delete the pull request and submit new one.

so far i have done these steps:

1) i have forked your repository and clone it to local machine.

2) i run setup.sh and created ahmed2022re with journal and openreview folder

3) i have placed my latex code in content.tex and all import lines in packages.tex

4) next what i am thinking to do is create main.tex file and copy my bib file to journal/bibliography.bib file

5) run build.sh then i would be able to have article.pdf file in my journal folder?

question1: do i need to edit my metadeta before build.sh or i can do after build.sh?

question2: once all the data has been put in to the folder locally, how can i transport it to my repository or it will happen automatically??

question 3: after transferring all the data, then i have to create a pull request?

**Comment by koustuvsinha** [comment]
1. Yes, you should edit the metadata.yaml before running the build.sh script

2. Once your build is working, add only your folder in git (git add ahmed2022re) and commit + push it to your fork.

3. Yes, create a PR once you have commit + pushed your stuff in your fork.

Hope this helps!

**Comment by koustuvsinha** [comment]
Closing as communicated with authors separately.
